# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
# Zatial len frontend, backend potom; toto vyrieši problemy z niektorými sračkami ako verzie dependencies a ine hovna
# (možno to aj niečo dojebe ked niečo deprecuje)

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/frontend" # Location of package manifests
    schedule:
      interval: "daily"
